USE SCOTT;
select * from EMP;
-- WAQTD details of employees if their annual_Salary is more than 9000 and display its half salary.
select ename, sal*6 as "Half_Annual" from EMP where sal*12 > 9000;

-- WAQTD names and job and salary of the employee who is working as clerak;
select ename "NAME", job, Sal from EMP where job = 'clerk';

-- AND Operators
-- write a query to display details of emp working as analyst and their salary should ve less than 5000
select * from emp where job = 'Analyst' AND sal < 5000;

-- WAQTD details of emp along with HAlf_term salary if they are hired after 1980 and earning more than 2000 and working as a manager
Select EMP.*, sal*6 "HALF_TERM" from EMP where hiredate > 1980 AND  sal>2000 AND job = 'Manager';
-- WAQTD DETAILS OF EMPLOYEE HIRED IN THEW YEAR OF 1980 AND THEIR HAL-TERM IS LESS THAN 700;
SELECT * 
FROM EMP 
WHERE hiredate >= '1980-01-01' AND  hiredate <= '1980-12-31' AND sal* 6<7000;


-- OR operator:
-- WAQTD details of employee who is ceo or sal is 2000;

Select *
from emp
where job = 'CEO' OR sal >2000;

-- WAQTD detials of employee working as analayst or clerk or salesman.
select * 
from emp
where job ='clerk' OR job ='analyst' OR job='salesman';

-- WAQTD details of employees if they are working as salesman or anlayst but they should earn more than 2000.

select *
 from emp
 where (job ='salesman' OR job='analyst') AND sal >2000;
 
 -- WAQTD DETAILS OF EMPLOYEE WORKING AS SALESMAN OR MANAGER EARNING MORE THAN 2000 AND LESS THAN 5000 AND HIRED AFTER 1982 AND BEFORE 1987
 
SELECT *
FROM EMP
WHERE (JOB = 'SALESMAN' OR JOB = 'MANAGER') AND SAL > 2000 AND SAL<5000 AND HIREDATE >'1982-12-31' AND HIREDATE < '1987-01-01';


-- NOT OPERATOR
-- WAQTD DEATILS OF EMPLOYEE WHO EARNS MORE THAN 2000 BUT THEIR JOB SHOULD NOT MANAGER;
SELECT * 
FROM EMP
WHERE NOT JOB = 'MANAGER' AND SAL>2000;

-- WAQTD DEATILS OF EMPLOYEES IF THEY ARE NIT WROKING AS MANAGER AOR SALESMAN BUT THETY ARE EARNING ANNUAL_SALAY LESS THAN 15000.
SELECT * 
FROM EMP
WHERE NOT JOB = 'MANAGER' AND NOT JOB='SALESMAN' AND SAL*12 <15000;

-- WAQTD DETAILS OF EMPLOYEE WORKING IN DEPTNO 10,20,30,40. 
-- FOR MULTIPLE CONDITIONS : IN
-- WAQTD DETAILS OF EMPLOYEE ANALYST,SALESMAN , CLREK, HIRED AFTER 1980 IN DEPARTMENT NUMBER 10,30;
SELECT * 
FROM EMP
WHERE JOB IN('SALESMAN','ANALYST','CLERK') AND HIREDATE > '1980-12-31' AND DEPTNO IN (10,30);

-- NOT IN OPERATOR
-- WAQTD NAME JOB AND HIER DATE OF EMPLOYE WHO IS HIRED BEFORE 1987 WORKING AS CLREK AND MANAGER BUT NOT WORKING IN DEPARTMENT NUMBER IN 20,30
SELECT *
FROM EMP
WHERE HIREDATE < '1987-01-01' AND JOB IN('CLREK', 'MANAGER') AND DEPTNO NOT IN(20,30);


-- BETWEEN OPERATOR

-- DETAILS OF EMPLOYEES ALONG WITH HALFTERM SALARY IF THEY ARE EARNING IN THE RANGE OF 1000 TO 5000 BUT THEY ARE NOT WORKING AS SALESMAN OR ANALAYST.
SELECT *, SAL*6 "HALF_TERM"
FROM EMP
WHERE SAL BETWEEN 1000 AND 5000
AND JOB NOT IN('SALESMAN','ANALYST');

-- WQT DETAILS OF EMPLOYEES IF THEY ARE HAVING SALARY MORE THAN 2000 AND LESS THAN 6000 AND THEY ARE HIRED AFTER 1978 AND BEFORE 1986;
SELECT * 
FROM EMP
WHERE SAL BETWEEN 2001 AND 5999
AND HIREDATE BETWEEN '1978-12-31' AND '1986-01-01';


-- NOT BETWEEN 

-- WAQTD DETAILS OF THE EMPLOYEES IF EMPLOYEES AARE NOT EARNING IN THE RANGE OF 1000 AND 3000;
SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 3000;

-- WAQTD DETAILS OF EMPLOYEE IF EMPLOYEE ARE NOT HIRED IN THE YEAR OF 81

-- WAQTD ENAME, SAL, HIREDATE, IF EMPLOYEE IS NOT HIRED AFTER 81 BUT BEFOR 87;

SELECT ENAME, SAL, HIREDATE
FROM EMP
WHERE HIREDATE NOT BETWEEN'1981-01-01' AND '1986-12-31';


-- IS OPERATOR:
-- WAQTD DETAILS WHO ARE NOT EARNING COMMISSION ;
SELECT *
FROM EMP
WHERE COMM IS NULL OR COMM = 0; -- FOR ZERO NOT NULL

-- WAQTD DETAILS OF EMPLYEE WHO DONT HAVE REPORTING MANAGER HE IS EARNING MORE THAN 3000 FOR LESS THAN 6000
SELECT *
FROM EMP
WHERE MGR IS NULL AND SAL BETWEEN 3000 AND 6000;


-- IS NOT : IT IS SPECIAL TYPE OF OPERATOR WHICH IS USED TO COMPARE WITH NOT NULL VALUE.
-- WAQTD NAME OF EMPLOYEE WHO EARNS COMMISSION.
SELECT ENAME
FROM EMP
WHERE COMM IS NOT NULL AND COMM>0;

-- WAQTD DETAILS OF EMPLOYEE WHO IS NOT EARNING COMMISIION BUT THEY HAVE REPORTING MANGER
SELECT * 
FROM EMP
WHERE (COMM IS NULL OR COMM =0 ) AND MGR IS NOT NULL;

-- lIKE: IT IS USED TO MATCH PATTERN
-- SYNTAX: COUMN-NAME/ EXPRESSION LIKE 'PATTERN_TO _MATCH'
--  TO ACHEIVE PATTERN MACTHING WE HAVE TWO SPECAIL CHARCHETER
-- 1. % AND 2.-
-- 1. %: IT ACCEPT ANY NUMBER OF CHARCTER. ANY NUMBER OF TIME AND NO CHARCTER. FOR FIRST 'A%' , FOR LAST '%A', FOR IN BETWEEN '%A%';
-- 2. -: 
-- WAQTD DETAILS OF EMPLOYEE IF THEY HAVE CHARACTER A AS A FIRST CHARCTER IN THEIR NAME
SELECT * 
FROM EMP
WHERE ENAME LIKE 'A%';

-- WAQTD DETAILS OF EMPLOYEE IF THEY HAVE CHARACTER 'MAN' IN THERI JOB;
SELECT *
FROM EMP
WHERE JOB LIKE 'MAN%';

-- WAQTD DETAILS OF EMPLOYE IF THEY HAVE CHARCTER A OR S IN THEIR JOB AND THEIR SALARY IS STARTING WITH DIGIT OF 50;

SELECT * 
FROM EMP
WHERE (JOB LIKE '%A%' OR JOB LIKE '%S%') AND SAL LIKE '50%';

-- 2. _ : IT CAN ACCEPT ANY CHARCTER BUT ONLY ONE CHARCTER
-- EXAMPLE: 
-- SECONF CHARCTER IS A: '_A%';
-- THIRD CHARACTER IS A: '__A%'
-- SECOND LAST CHARCTER IS A: '%A-'
-- THIRD LAST CHARCTER IS A: '%A___'
-- STARTS WITH A AND SECOND LAST CHARCTER IS N:
-- HAS EXACTLY 5 CHARCTER:

-- WAQTD DETAILS OF EMPLOYEE  ID THEY ARE HIRED IN THE MONTH OF DEC

SELECT * 
FROM EMP
WHERE HIREDATE LIKE '____-12-__'; -- OR WE CAN USE %-12-%;

-- WAQTD DETAILS OF EMPLOYEE IF THEY ARE HIRED IN THE YR OF 1981 AND THEY ARE HAVING 4 DIGIT SALARY
SELECT * 
FROM EMP
WHERE HIREDATE LIKE '1981%' AND SAL LIKE '____.%';

-- NOT LIKE OPERATOR: IT IS SIMILAR TO LIKE OPERATOR INSTEAD OF SLECTING THE PATTERN IT WILL REJECT THOSE PATTERN

-- WAQTD NAME, ANNUAL-SALARY AND HALF-TERM SALARY ALONG WITH JOB IF THE EMPLOYEES ARE HIRED AFTER 82 AND BEFORE 86 
--  AND THEY DO NOT HAVE 3 DIGIT SALARY BUT THEY ARE WOTKING IN DEPTNO 10 OR 30 AS A SALESMAN OR ANALAYST BUT THEY HAVE REPORTIN MANAGER.

SELECT ENAME, SAL*6 AS "HALSF_TERM_SAL", SAL*12 AS "ANNUAL_SAL", JOB 
FROM EMP
WHERE HIREDATE BETWEEN '1982-01-01' AND '1985-12-31' 
AND SAL NOT LIKE '___.%' 
AND DEPTNO IN(10,30) 
AND JOB IN('SALESMAN','ANALAYST') 
AND MGR IS NOT NULL;

-- CONCATENATION (||) : TO MERGE THE TWO CPLUMNS AND STRING; EXAMPLE: SELECT ENAME || JOB FROM EMP; OR SELECR 'MR.' || ENAME FROM EMP;
-- IT WILL WORKS ON ORCLESQL ONLY NOT IN MYSQL AND POSTRESQL SO THERE WE USE FUNCTION CALLED CONCAT:
-- EG: SELECT CONACT (ENAME,SAL) AS NAMES FROM EMP;

SELECT CONCAT(ENAME,SAL) 'NAME'
FROM EMP;

SELECT CONCAT('MR.',ENAME) 'NAME'
FROM EMP;

-- FUNCTION:  THESE ARE A BLOCK OF CODE OR LIST OF INBSTRUCTIONS WHICH IS USED TO PERFORM A SPECIFIC TASK
-- TYPES OF FUNCTIONS IN SQL:
-- 1. IN-BULIT FUNCTIONS AND 2. USER-DEFINED FUNCTION

-- 1. TYPE OF IN-BULIT FUNCTIONS:
-- A. SINGLE ROWS FUNCTION: ONE INPUT -> ONE OUTPUT, TWO INPUT -> TWO OUTPUT, N-INPUT -> N-OUTPUT;  ROW BY ROW EXECUTIONS  
-- B. MULTI ROW FUNCTIONS/ AGGERGATE / GROUP FUNCTION: ONE INPUT -> ONE OUTPUT, TWO INPUT -> ONE OUTPUT, N-INPUT -> ONE OUTPUT
--  MAX, MIN, COUNT, SUM ,AVG // GROUP BY EXCETIONS

-- CHARCTERISTICS OF MULTI-ROWS FUNCTION:
-- FOR MULTI-ROWS FUNCTIONS() WE CAN PASS ONLY ONE ARGUMSNTS;
-- FOR MULTI-ROWS FUNCTIONS() WE CANNOT PASS ANY OTHER COULMN NAME IN THE SEELCT CLAUSE.
-- MULTI-ROWS FUNCTIONS IGNORES NULL VALUE.
-- IN WHERE CLAUSDE WE CANNOT PASS MULTI ROWS FUNCTIONS.
-- COUNT IS THE ONLY ONE MULTI-ROWS FUNCTION WHICH ACCEPTS * AS AN ARGUSMENT EG: COUNT(*)
-- SUM() AND AVG() ACCEPTS ONLY ONE NUMBER AS AN ARGUMENTS.

-- WAQTD NUMBER OF EMPLOYEES ALONG WITH THEIR MAXM SALARY IF THEY ARE WORKING IN DEPTNO 10 OR 30
SELECT COUNT(*),MAX(SAL)
FROM EMP
WHERE DEPTNO IN(10,30);

-- WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 10 IF THEY HAVE REPORTING MANAGER
SELECT COUNT(*)
FROM EMP
WHERE DEPTNO = 10 AND MGR IS  NOT NULL;

-- WAQTD NUMBER OF EMPLOYEE WORKING IN EACH DEPT;
SELECT COUNT(*)
FROM EMP
WHERE DEPTNO IN(10,20,30);


-- GROUP BY: IT IS USED TO GROUP THE RECORDS
-- SYNTAX SELECT GROUP_FUNCTION/ GROUP_BY_EXPRESSION FROM THE TABLE_NAME [WHERE <FILTER-COND>] GROUP BY COLUMN-NAME/EXPRESSION
-- GROUP BY CLAUSE IS USED TO GROUP THE RECORDS
-- GROUP BY CLAUSE EXECUTES ROWS BY ROWS.
-- AFTER THE EXECTIONS OF GROUP BY CLAUSE WE ARE GETTING GROUPS.
-- ANY CALUSE EXCEUTES AFTER GROUP BY CLAUSE IT EXECITES GROUP BY GRPUP;
-- THE COLUMNS NAME/EXPRESSION USED FOR GROUPING CAN BE WRITTEN IN THE SELECT CLAUSE THAT WILL BE CALLED AS GROUP BY EXPRESSION
-- GROUP BY CLAUSE CAN BE USED WITH OR WITHOUT WHERE CLAUSE.

SELECT DEPTNO, COUNT(*) AS 'NUM_OF_EMP'
FROM EMP
GROUP BY DEPTNO;


-- WAQTD MAXIMUM SALARY OF EMPLOYEE IN EACH DEPT.

SELECT MAX(SAL), DEPTNO
FROM EMP
group by DEPTNO;

-- WAQTD NUMBER OF EMPLOYEE IS WORKING IN EACH DEPT IF THEIR SALARY IS MORE THAN 2000 AND THEY ARE WOTRKING AS CLERK.

SELECT COUNT(*), DEPTNO
FROM EMP
WHERE SAL >2000 AND JOB = 'CLERK'
GROUP BY DEPTNO;

-- WAQTD UNIQUE SALARIES:
SELECT SAL
FROM EMP
GROUP BY SAL;

-- WAQTD NUMBER OF TIMES SALARIES HAVE BEEN REPEATED IN EMP TABLE;
SELECT SAL, COUNT(*)
FROM EMP
GROUP BY SAL;

-- WAQTD TOTAL SALRIES OF EMPLYEES WORKING IN EACH JOB IF THEIR JOB IS CLERK OR SALEMAN AND THEY ARE HIRED IN THE YEAR OF 1981.

SELECT SUM(SAL),JOB
FROM EMP 
WHERE JOB IN('CLERK', 'SALESMAN') AND HIREDATE LIKE '1981%'
GROUP BY  JOB;

-- WAQTD NUMBER OF EMPLOYEE WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 EMPLOYEES WORKING IN EACH DEPT.

-- HAVING CLAUSE:  IT IS USED TO FITER THE GROUPS.
-- SYNTAX: SELECT GROUP_FUNCTION/GROUP_EXPRESSION FROM TABLE_NAME [WHERE <FILTER-COND>] GROUP BY COLUMN_NAME/EXPRESSION HAVING <GROUP-FILTER-COND>;
-- POINTS FOR HAVING CLAUSE:
-- HAVING CLAUSE IS USDED TO FILTER THE GROUPS
-- HAVING CLAUSE EXECUTES GROUP BY GROUP.
-- HAVING CLAUSE EXECUTES AFTER THE EXCETIONS OF GROUP BY CLAUSE.
-- WE WRITE GROUP FILTER COND IN HAVING CLAUSE.
-- WE CAN PASS MULTI -ROWS FUNCTION IN HAVING CLAUSE.
-- TO USE HAVING CLAUSE GROUP CLAUSE IS MANDATORY
-- WE CAN PASS MUTLIPLE CONDTIONS IN HAVING CLAUSE BY USING LOGICAL OPERATORS.

SELECT DEPTNO, COUNT(*)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) >= 2; -- WE CANNOT PASS THIS CONDTION IN WHERE CLAUSE BECAUSE IT WORKS ONLY GROUPS; WE GET FILTERED GROUPS

-- WAQTD MAXIMUM SALARY AND MIN SALARY OF EMPLOYEE WORKING IN EACH JOB IF MAXIMUM SLARY OF EACH JOB IS MORE THAN 3000.
SELECT MAX(SAL),MIN(SAL), JOB
FROM EMP
GROUP BY JOB
HAVING MAX(SAL)>3000;

-- WAQTD TOTAL SALARY OF EMPLOYEE WORKING IN EACH DEPT IF THEIER SALARY IS MORE THAN 2000
-- AND AVG SALARY NEEDED TO PAY TO THE EMPLOYEE IS LESS THAN 2000

SELECT DEPTNO, SUM(SAL) AS TOTAL_SAL, AVG(SAL) AS AVG_SAL
FROM EMP
WHERE SAL > 2000
GROUP BY DEPTNO
HAVING AVG(SAL) < 2000;


-- WAQTD REPEATED SALARY

SELECT SAL,COUNT(*)
FROM EMP
GROUP BY SAL
HAVING COUNT(*)>=2;

SELECT ENAME
FROM EMP
GROUP BY HIREDATE
HAVING COUNT(*) >=2;

-- WAQTD MAXM SAL OF EMPLOYEE WORKING IN EACH JOB IF THEIR JOB IS NALAYST OR CLERK AND THEIR DEPTNO IS 20
--  BUT NOT THEIR MAXM SALARY IS MORE THAN 2000 AND THEIR SALARY IS MORE THAN 1000

SELECT JOB, MAX(SAL) AS MAX_SAL
FROM EMP
WHERE JOB IN ('ANALYST', 'CLERK')
AND DEPTNO = 20
AND SAL > 1000
GROUP BY JOB
HAVING MAX(SAL) < 2000;


-- SUB-QUERIES:
-- A QUERY WHICH IS WRITTEN INSIDE ANOTHER QUERY IS CALLED SUB-QUERY.
-- 1. OUTER QUERY
-- 2. INNER QUERY: FIRST INNER QUERY EXECUTES
-- CASE 1: EXAMPLE
-- WAQTD DETAILS OF EMP EARNING MORE THAN SMITH;

SELECT *
FROM EMP
WHERE SAL >( 
SELECT SAL
FROM EMP
WHERE ENAME LIKE'SMITH');

-- WAQTD NAME OF THE EMPLYEES EARNING LESS THAN JONES;
SELECT ENAME 
FROM EMP
WHERE SAL <(
SELECT SAL
FROM EMP 
WHERE ENAME LIKE 'JONES'
);

-- WAQTD NAME OF THE EMPLOYEES ALONG WITH ANUUAL SALRY WHO ARE HIRED BEFORE JAMES AND EARNING MORE THAN 1000.
SELECT ENAME, SAL*6 'ANNUAL'
FROM EMP 
WHERE HIREDATE < (
SELECT HIREDATE
FROM EMP
WHERE ENAME LIKE 'JAMES') AND SAL > 1000;

-- WAQTD NAME, SAL, DEPTNO, OF THE EMPLOYEE IF THE EMPLOYEE EARN MORE THAN 2000 AND WORK IN THE SAME DEPT AS JAMES

SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE SAL > 2000
AND DEPTNO = (
SELECT DEPTNO 
FROM EMP
WHERE ENAME LIKE 'JAMES');

-- WAQTD DETAILS OF THE EMPLOYEE EARNING MORE THAN SMITH LESS THAN KING

SELECT *
FROM EMP
WHERE SAL > (
SELECT SAL
FROM EMP
WHERE ENAME LIKE 'SMITH')
AND SAL < (
SELECT SAL
FROM EMP
WHERE ENAME LIKE 'KING');

-- WAQTD NAMES OF THE EMPLOYEE WORKING IN SAME DEPT AS JAMES AND
-- EARNING SALSRY MORE THAN ADAMS AND WORKING IN THE SAME ROLE AS MILLER AND HIRED AFTER MARTIN

SELECT ENAME
FROM EMP
WHERE DEPTNO = (
SELECT DEPTNO
FROM EMP
WHERE ENAME LIKE 'JAMES')
AND SAL >(
SELECT SAL
FROM EMP
WHERE ENAME LIKE 'ADAMS')
AND JOB = (
SELECT JOB 
FROM EMP
WHERE ENAME LIKE 'MILLER')
AND HIREDATE >(
SELECT HIREDATE
FROM EMP
WHERE ENAME LIKE 'MARTIN');

-- WAQTD NAME AND HIREDATE OF THE EPLOYEE WHO'S NAME ENDS WITH S AND HIRED AFTER JAMES

SELECT ENAME, HIREDATE
FROM EMP
WHERE ENAME LIKE '%S' AND HIREDATE > (
SELECT HIREDATE
FROM EMP
WHERE ENAME LIKE 'JAMES');

-- CASE2: WHEN WE ARE JUMING FROM ONE TABLE TO ANOTHER TABLE.
-- WAQTD DNAME OF WARD

SELECT DNAME
FROM DEPT
WHERE DEPTNO = (
SELECT DEPTNO
FROM EMP
WHERE ENAME LIKE 'WARD'
);

-- WAQTD DNAME OF THE EMPLOYEE WHOSE NAME IS MILLER
SELECT DNAME 
FROM DEPT
WHERE DEPTNO =
(SELECT DEPTNO
FROM EMP
WHERE ENAME LIKE 'MILLER');

-- SINGLE ROW SUBQUIREY
-- if the subquery returns exactly one value, then it is known as single row subquery
-- it it returns only one value, then we can ues the normal operators or the special operators to compare the values

-- MULTI ROW SUBQUERY
-- ID THE SUBQUERY RETURNS EXACTLY MORE THAN ONE VALUE, THEN IT IS KNOWN AS MUTLI ROW SUBQURY.
-- IF IT RETURN MORE THAN ONE VALUE, THEN WE CANNOT USE THE NORMAL OPERATORS. WE HAVE TO USE SPECAILS OPERTOR TO COMPARE THEM

-- WAQTD DETAILS OF EMPLYEE WHO ARE WORKING IN THE LOCATION NEW YORK

SELECT *
FROM EMP
WHERE DEPTNO IN (
SELECT DEPTNO 
FROM DEPT 
WHERE LOC LIKE 'NEW YORK');

-- WAQTD ALL THE DETAILS OF THE EMPLOYEE WORKING IN THE SAME DESIGNATION AS MILLER AND WORK IN LOCATION NEW YOTK.
SELECT *
FROM EMP
WHERE DEPTNO IN (
SELECT DEPTNO 
FROM EMP
WHERE ENAME LIKE 'MILLER') AND DEPTNO IN (
SELECT DEPTNO 
FROM DEPT 
WHERE LOC LIKE 'NEW YORK');


-- WAQTD NUMBER OF EMPLOYEE WORKING AS CLREK IN THE SAME DEPTNO AS SMITH AND EARNING MORE THAN KING 
-- HIREDATE AFTER MARTIN IN THE LOCATION OF BOSTON
SELECT COUNT(*) 
FROM EMP
WHERE JOB LIKE 'CLERK' AND DEPTNO = (
SELECT DEPTNO
FROM EMP 
WHERE ENAME LIKE 'SMITH') 
AND SAL >(
SELECT SAL
FROM EMP
WHERE ENAME LIKE 'KING')
AND HIREDATE > (
SELECT HIREDATE 
FROM EMP
WHERE ENAME LIKE 'MARTIN')
AND DEPTNO IN (
SELECT DEPTNO
FROM DEPT
WHERE LOC LIKE 'BOSTON');
-- WAQTD DNAME OF CLREK

SELECT DNAME 
FROM DEPT
WHERE DEPTNO IN ( SELECT DEPTNO
FROM EMP
WHERE JOB LIKE 'CLERK');

-- WAQTD NUMBER OF EMPLOYEES WORKING AS CLERK OR SALESMAN EARNING MORE THAN 8000
-- AND WORKING IN THE LOCATION OF NEW YORK OR DALLAS IN EACH DEPARTMENT.

SELECT COUNT(*),DEPTNO
FROM EMP
WHERE JOB IN ('CLERK' , 'SALESMAN') AND SAL >800 AND  DEPTNO IN (
SELECT DEPTNO
FROM DEPT
WHERE LOC IN ('NEW YORK', 'DALLAS'))GROUP BY DEPTNO;

-- WAQTD DETIALS OF EMPLOYEE WHO IS EARNING MAXIMUM SALARY
SELECT *
FROM EMP
WHERE SAL = (
SELECT MAX(SAL)
FROM EMP);

-- WQTD 2ND MAXIMUM SALARY.
SELECT MAX(SAL) 
FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP);

-- NESTED SUBQURIES
-- A SUBQUERIES WHICH IS WRITTEN INSIDE ANOTHER SUBQUERRY IS KNOWN AS NESTED SUBQUERY 
-- WE CAN NEST UPTO 255 SUBQURIES.


-- WAQTD DETIALS OF EMPLOYEE WHO IS EARNING 2ND MINMUM 

SELECT * 
FROM EMP
WHERE SAL = (SELECT MIN(SAL)
FROM EMP
WHERE SAL >( SELECT MIN(SAL)
FROM EMP)
); 

-- WAQTD LOC OF EMPLOYEE WHO IS EARNING 3RD MAXIMUM SALARY;

SELECT LOC
FROM DEPT
WHERE DEPTNO IN 
(SELECT DEPTNO 
FROM EMP
WHERE SAL IN ( SELECT MAX(SAL)
FROM EMP
WHERE SAL < 
(SELECT MAX(SAL)
FROM EMP
WHERE SAL < ( SELECT MAX(SAL)
FROM EMP 
)
)
)
);

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEE WHO IS EARNING MORE THAN CLERK;

SELECT ENAME, HIREDATE
FROM EMP
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'CLERK');

-- Subquery operators:
-- ALL: IT IS SPECIAL OPERATOR WHICH HAS TO BE USED ALONG WITH RELATIONAL OPERATORS TO COMAPRE THE VALUES PRESENT IN RHS.
-- ALL OPERATOR RETURN TRUE IF ALL THE VALUES PRESENT AT RHS SATISFES THE CONMDTION.

-- WAQTD DETAILS OF EMPLOYEE EARNING LESS THAN SALESMAN AND HIRE DATE AFTER ALL THE CLERKS

SELECT *
FROM EMP
WHERE SAL < ALL(
SELECT SAL 
FROM EMP 
WHERE JOB LIKE 'SALESMAN') 
AND HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE JOB LIKE 'CLERK') ;


-- WAQTD DETAILS OF EMPLOYEE EARNING MORE THAN THE EMPLOYEEE WHO IS HAVING CHARCTER 'A' IN HIS NAME AND 
-- EARNING LESS THAN THE EMPLOYEE WHO IS WORKING IN THE LOCATION OF CHICAGO

SELECT * 
FROM EMP
WHERE SAL > ALL
(SELECT SAL
FROM EMP
WHERE ENAME LIKE '%A%') 
AND SAL < ALL(SELECT SAL
 FROM EMP
 WHERE DEPTNO  IN ( SELECT DEPTNO
 FROM DEPT
 WHERE LOC LIKE 'CHICAGO') );
 
 -- ANY:
 -- IT IS A SPECIAL OPERATOR WHICH HAS TO BE USED ALONG WITH RELATIONAL OPERATORS TO COMAPRE THE VALUES PRESENT IN RHS.
 -- ANY OPERATOR RETURNS TRUE IF ANY ONE OF VALUE IS PRESENT AT RHS SATISFES TH COMNDTION.
 
 -- WAQTD DETAILS OF EMPLOYEE EARNING MORE THAN ANY ONE OF THE CLERK  / ATLEAST A CLERK
 
 SELECT *
 FROM EMP
 WHERE SAL > ANY
 (SELECT SAL
 FROM EMP
 WHERE JOB LIKE 'CLERK');
 
 -- WAQTD NAME AND HIREDATE AND ANNUAL SALARY OF THE EMPLOYEE IF HIS ANNUAL SALARY IS GREATER THAN ANY ONE OF CLERK ' S ANNUAL SALRY BUT
 -- THOSE EMPLOYEE ARE HIRED AFTER MANAGER
 
 SELECT ENAME, HIREDATE, SAL*12
 FROM EMP
 WHERE SAL*12 > ANY( SELECT SAL*12 FROM EMP WHERE JOB LIKE 'CLERK')
 AND HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE JOB LIKE 'MANAGER');
 
 -- WAQTD NAMES AND HALF TERM SLARY OF AN EMPLOYEE WHO IS HIRED AFTER ADAMS EARNING LESS THAN THE EMPLOYEES 
 -- WHO IS HAVING CHARCTER 'MAN' IN HIS JOB AND THEY ARE HIRED AFTER ATLEAST A SALESMAN IF THEIR SALARY IS IN THE RANGE OF 1000 TO 5000;
 
SELECT ENAME, SAL*6
FROM EMP
WHERE HIREDATE > 
(SELECT HIREDATE FROM EMP WHERE ENAME LIKE 'ADAMS') AND
SAL < ALL ( SELECT SAL FROM EMP WHERE JOB LIKE  '%MAN%') AND
HIREDATE > ANY( SELECT HIREDATE FROM EMP WHERE JOB LIKE 'SALESMAN') AND
SAL BETWEEN '1000' AND'5000';

-- JOINS :
-- THE PROCESS OF RETRIEVING THE DATA FREOM THE MULTIPLE TABLES SIMULTANEOUSLY IS KNOWN AS JOINS.

-- TYPE OF JOINS:
-- 1. CARTESIAN JOIN/ CROSS JOIN
-- 2. INNER JOIN / EQI JOIN
-- 3. NATURAL JOIN
-- 4. SELF JOIN
-- 5. OUTER JOIN : LEFT OUTER JOIN, RIGHT OUTER JOIN, AND FULL OUTER JOIN.

-- 1. CARTESIAN JOIN/CROSS JOIN: IN CARTESIAN JOIN RECORD OF TABLE 1 WILL MERGE WITH ALL THE RECORDS OF TABLES2.
-- SYNTAX ANSI: SELECT COLNAME/EXP FROM TABLENAME1 CROSS JOIN TABLENAME2;
-- SYNTAX ORCLE: SELECT COLNAME/EXP FROM TABLENAME1,TABLENAME2;

SELECT *
FROM EMP CROSS JOIN DEPT; -- WE GET MULTIPLICATION OF DATA EX: DATA IN EMP IS 4 AND DEPT HAVE 3 THEN I WILL GET 3*4 = 12 ROWS/DATA
-- ALL THE DETAILS OF THE EMP IS MERGE WITH DEPT
-- SO WE CAN USE IT IN THOSE TABLE THERE IS NO CONNECTION BETWEEN TWO TABLE 

-- INNER JOINS/EQI JOIN: IT IS USED  TO OBTAIN ONLY MATCHING RECORDS
-- SYNTAX: ANSI: SELECT COLNAME/EXP FROM TABLE1 INNER JOIN TBALE2 ON <JOIN_CONDITION>;
-- ORCLE : SELECT COLNAME/EXP FROM T1, T2 WHERE <JOIN_CONDITION>;

-- JOIN CONDTIONS: IT USED TO MERGE TWO TABLES 
-- SYNTAX TABLENAME1.COLNAME = TABLENAME2.COLNAME
SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;
 -- WAQTD DETAILS OF EMPLOYEES AND THEIR DEPARTMENTS IF THE EMPLOYEE ARE EARNING MORE THAN 3000.
 
 SELECT *
 FROM EMP INNER JOIN DEPT
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE SAL >3000;
 
 -- WAQTD DETAILS OF DEPARTMENT ALONG WITH THE EMPLOYEE NAMES IF EMPLOYEES ARE WORKING IN THE LOCATION OF CICAGO
 -- AND THEY ARE HIRED AFTER CLERK
 
 SELECT *
 FROM EMP INNER JOIN DEPT
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE LOC LIKE 'CICAGO' AND HIREDATE >( SELECT HIREDATE FROM EMP WHERE JOB LIKE 'CLERK');
 
 -- WAQTD NUMBER OF EMPLOYEE WORKING IN EACH DEPARTMENT IF THEIR MAXIUM SALARY IS MORE THAN 2000 AND THEIR LOC IS NEW YORK OR CHICAGO AND THEY ARE 
 -- HIRED AFTER THE EMPLOYEE WHO IS NOT EARNING COMMISIION
 
SELECT COUNT(*)
FROM EMP 
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.SAL > 2000 
  AND DEPT.LOC IN ('NEW YORK', 'CHICAGO') 
  AND EMP.HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE COMM IS NULL OR COMM = 0)
 GROUP BY DEPT.DNAME;
 
 -- WAQTD DETAILS OF FORD'S MANAGER
 SELECT *
 FROM EMP 
 WHERE EMPNO = (SELECT MGR 
 FROM EMP
 WHERE ENAME LIKE 'FORD');
 
 -- WAQTD NAME AND HIREDATE OF ADMANS MANAGER
 SELECT ENAME, HIREDATE
 FROM EMP
 WHERE EMPNO = (SELECT MGR
 FROM EMP
 WHERE ENAME LIKE 'ADAMS');
 
 -- WAQTD NAME AND HIREDATE OF SMITH'S MANAGER 'S MANAGER;
 
 SELECT ENAME, HIREDATE
 FROM EMP
 WHERE EMPNO =(SELECT MGR
 FROM EMP
 WHERE EMPNO = (SELECT MGR 
 FROM EMP 
 WHERE ENAME LIKE 'SMITH')
 );
 
 -- WAQTD DETAILS OF EMPLOYEES REPORTING TO KING;
 
 SELECT * 
 FROM EMP
 WHERE MGR = 
 (SELECT EMPNO
 FROM EMP
 WHERE ENAME LIKE 'KING'); 
 
 -- WAQTD DETAILS OF EMPLOYEE AND THEIR MANAGER DETAILS

-- SELF JOIN: JOINING A TABLE BY ITSELF, JOINING SAME 2 TABLES IS KNOWN SELF-JOIN
-- SYNTAX: ANSI -> SELECT COLNAME/EXP FROM T1 AND T2 ON <JOIN_COND>; ORCLE-> SELECT COLNAME/EXP FROM T1, T2 WHERE JOIN<JOIN_COND>;
USE SCOTT;

-- WAQTD EMP AND THEIR MANAGER DETAILS
SELECT *
FROM EMP  E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO;

-- WAQTD NAMES OF EMPLOYEE AND THEIR MANAGERS IF EMPLOYEE ARE EARNING MORE THAN 2000

SELECT E1.ENAME EMPLOYEE, E2.ENAME MANAGER
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.SAL >2000;

-- WAQTD NAME OF EMPLOYEE AND THEIR MANAGER IF EMPLOYEE ARE EARNING MORE THAN THEIR MANAGERS AND MANAGERS ARE HIRED AFTER CLERK.
SELECT E1.ENAME EMPLOYEE, E2.ENAME MANAGER
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.SAL > E2.SAL AND E2.HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE JOB LIKE 'CLERK');

-- WAQTD DETAILS OF EMPLOYEE AND THEIR MANAGERS NAME IF EMPLOYEE ANUUAL SALARY IS GREATER THAN THEIR MANAGER ANNUAL SALARY
 -- IF EMPLOYEE ARE HIRED AFTER THE EMPLOYEE WHO IS WORKING IN LOCATION OF NEW WORK AND MANAGER ARE HAVING CHARCTER 'A' IN THEIR NAME.
 SELECT E1.EMPNO AS EMP_ID,
       E1.ENAME AS EMPLOYEE_NAME,
       E1.SAL AS EMP_SAL,
       E2.ENAME AS MANAGER_NAME,
       E2.SAL AS MANAGER_SAL
FROM EMP E1
JOIN EMP E2
  ON E1.MGR = E2.EMPNO
WHERE (E1.SAL*12) > (E2.SAL*12)
  AND E1.HIREDATE > ALL (
        SELECT HIREDATE
        FROM EMP
        WHERE DEPTNO IN (
            SELECT DEPTNO
            FROM DEPT
            WHERE LOC = 'NEW YORK'
        )
      )
  AND E2.ENAME LIKE '%A%';
  
  
  
  
  -- WAQTD DETAILS OF EMPLOYEE AND THEIR MANAGER AND THEIR MANGER'S MANGER
  
SELECT *
FROM EMP E1
JOIN EMP E2
  ON E1.MGR = E2.EMPNO
JOIN EMP E3
  ON E2.MGR = E3.EMPNO;
  
-- WAQTD DETAILS OF EMPLOYEE AND THEIR MANAGERS AND MANGER'S MANAGER'S EMPLOYEE ARE EARNING MORE THAN THEIR MANAGER AND  
-- MANAGER ARE HIRED AFTER BLAKE AND MANAGER'S MANAGER ARE WORKING IN DEPTNO 10 OR 30 
-- IF ALL OF THEM HAVE CHARCTER 'A' OR 'S' IN THERI NAME.

SELECT *
FROM EMP E1
JOIN EMP E2 ON E1.MGR = E2.EMPNO
JOIN EMP E3 ON E2.MGR = E3.EMPNO
WHERE E1.SAL > E2.SAL
  AND E2.HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'BLAKE')
  AND E3.DEPTNO IN (10, 30)
  AND (E1.ENAME LIKE '%A%' OR E1.ENAME LIKE '%S%')
  AND (E2.ENAME LIKE '%A%' OR E2.ENAME LIKE '%S%')
  AND (E3.ENAME LIKE '%A%' OR E3.ENAME LIKE '%S%');
 
 -- WAQTD NAME OF EMPLOYEE AND THEIR MANGER'S AND MANER'S MANAGER LONG WITH THEIR DEPARTMENT
 
 SELECT E1.ENAME, E2.ENAME, E3.ENAME,D1.DNAME,D2.DNAME,D3.DNAME
 FROM EMP E1 JOIN EMP E2
 ON E1.MGR = E2.EMPNO
 JOIN EMP E3
 ON E2.MGR = E3.EMPNO
 JOIN DEPT D1
 ON E1.DEPTNO = D1.DEPTNO
 JOIN DEPT D2
 ON E2.DEPTNO = D2.DEPTNO
 JOIN DEPT D3
 ON E3.DEPTNO = D3.DEPTNO;
 
 
 -- WAQTD NAMES AND HIREDATES OF THE EMPLOYEE IF THE EMPLOYEE ARE HIORE AFTER THEIR MANAGER AND MANAGER ARE HIRED AFTER ADAMS AND MANAGER' S
 --  MANAGER ARE EARNING MORE THAN CLERK AND EMPLOYTEE ARE WORKING IN RESEARCH DEPATMENT MANAGER ARE WORKING IN THE LOCATION OF CHICAGO AND
 -- MANAGER'S MANAGER ARE WORKING IN THE DEPTNO 20.
 
 
 SELECT E1.ENAME, E1.HIREDATE
 FROM EMP E1 JOIN EMP E2
 ON E1.MGR = E2.EMPNO
 JOIN EMP E3
 ON E2.MGR = E3.EMPNO
 JOIN DEPT D1
 ON E1.DEPTNO = D1.DEPTNO
 JOIN DEPT D2
 ON E2.DEPTNO = D2.DEPTNO
 JOIN DEPT D3
 ON E3.DEPTNO = D3.DEPTNO
 WHERE E1.HIREDATE > E2.HIREDATE
 AND E2.HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME LIKE 'ADAMS')
 AND E3.SAL > (SELECT SAL FROM EMP WHERE JOB LIKE 'CLERK')
 AND D1.DNAME LIKE 'RESEARCH'
 AND D2.LOC LIKE 'CHICAGO'
 AND D3.DEPTNO = 20;
 
 
 -- WAQTD LOC OF SALEMAN'S MANAGER'S MANAGER
 use scott;
 
SELECT D.LOC
FROM EMP E1                        -- E1 is the Salesman
JOIN EMP E2 ON E1.MGR = E2.EMPNO    -- E2 is the Manager
JOIN EMP E3 ON E2.MGR = E3.EMPNO    -- E3 is the Manager's Manager
JOIN DEPT D ON E3.DEPTNO = D.DEPTNO -- D is the Department of E3
WHERE E1.JOB = 'SALESMAN';
 

 -- NATURAL JOINS:
 -- IT HAS 2 BEHAVIOURS
 -- 1. IF THERE IS A CONNECTION BETWEEEN TWO TAABLES THEN IT WILL ACT LIKE INNER JOIN
 -- 2. IF THERE IS NO CONNECTION BETWEEN TWO TABLES THEN IT WILL ACT AS CROSS JOIN/CARTESIAN JOIN 
 -- SYNTAX: ANSi-> SELECT COLNAME/EXP FROM T1 NATURAL JOIN T2.
 
 
 -- OUTER JOIN: IT IS USED TO BTAIN UNMATCHED RECRODS
 -- TYPES OF OUTER JOIN:
 -- 1. LEFT OUTER JOIN, 2. RIGHT OUTER JOIN 3. FULL OUTER JOIN
 
 -- 1.LEFT OUTER JOIN: IT IS USED TO OBTAIN UNMATCHED RECORDS ONLY FROM THE LEFT TABLE ALONG WITH MACTHING RECORDS.
 -- SYNTAX ANSI-> SELECT COLNAME/EXP FROM T1 LEFT [OUTER] JOIN T2 ON<JOIN_COND>;
 -- ORACLE: SELECT COLNAME/EXP FROM T1,T2 WHERE T1.COLNAME = T2.COLNAME(+);
 
 -- WAQTD DETAILS OF EMPLOYEE AND THEIR DEPARTMENTS EVEN IF EMPLOYEES DOESN'T PRESENT IN ANY DEPARTMENT
 SELECT *
 FROM EMP LEFT JOIN DEPT # DUE TO THE LEFT JOIN WORD I WILL GET NOT MATCHING DATA
 ON EMP.DEPTNO = DEPT.DEPTNO; # DUE TO THIS STATEMENT I GET ALL THE MATCHING DATA.
 
 -- WE CAN SOLVE PROBLEM OF RIGHT OUTER JOIN USING LEFT OUTER JOIN
 
 -- WAQD DETAILS OF EMPLOYEES AND THEIR DEPARTMENT IF EMPLOYEE ARE HAVING CHARCTER 'A' IN HIS NAME AND 
 -- THEY ARE WORKING IN LOC NEW YORL AND DISPLAY THOSE EMPLOYEE WHO ARE NOT WORKING IN ANY DEPTARTMENT
 
SELECT *
FROM EMP
LEFT JOIN DEPT
  ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.ENAME LIKE '%A%'
  AND DEPT.LOC = 'NEW YORK';
  
  -- RIGHT OUTER JOIN: IT IS USED TO OBTAIN UMATCHED RECORDS ONLY FROM RIGHT TABLE, ALONMG WITH MATCHING RECORDS
  -- SYNTAX: ANSI-> SELECT COLNAME/EXP FROM T1 RIGHT[OUTER] JOIN T2 ON <JOIN_COND>;
  -- SYNTAX: ORCALE -> SELECT COLNAME/EXP FROM T1,T2 WHERE T1.COLNAME(+) = T2.COLNAME;
  
  -- FULL OUTER JOIN: IT IS USED TO OBTAINE UNMATCHED RECORDS FROM BOTH THE TABLE, ALONG WITH MATCHING RECORDS. IT DOES NOT WORK ON MYSQL
  -- SYNTAX; ANSI-> SELECT COLNAME/EXP FROM T1 FULL[OUTER] JOIN T2 ON <JOIN_COND>;
  
 --  SELECT * 
--   FROM EMP FULL OUTER JOIN DEPT
--   ON EMP.DEPNO = DEPT.DEPNO;

-- UNION : TO USE FULL OUTER JOIN BECAUSE IT IS NOT WORKING IN MYSQL.alter
SELECT * FROM EMP LEFT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
UNION
SELECT * FROM EMP RIGHT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;


-- CO-RELATED SUBQUERY: A QUERY WRITTEN INSIDE ANOTHER QUERY SUCH THAT OUTER QUERY AND THE INNER QUERY ARE DEPENDENT ON EACH OTHER,
--  THIS IS KNOW AS CO-RELATED SUBQUERY.
-- OUTER QUERY AND INNER QUEERY ARE INTERDEPENDENT TO EACH OTHER
-- POINTS:
-- OUTER QURIES EXECUTES FIRST, BUT PARTIALLY'
-- THE PARTIALLY EXECUTES OUTPUT IS GIVEN AS INPUT TO THE INNER QUERY
-- THE INNER QUERY EXECUTES COMPLETELY AND GENERATE THE OUTPUT
-- THE OUTPUT OF THE INNNER QUERY IS FED AS IN INPUT TO THE OUTER QUERY AND OUTER QUERY PRODUCES RESULT
-- THEREFORE, WE CAN STATE THAT THE OUTER QUERY AND INNER QUERY BOTH ARE INTERDEPENT.
USE SCOTT;
-- TO FIND NTH MAXM SALARY FOR EXAMPLE 4 -1
SELECT E1.SAL
FROM EMP E1
WHERE 4-1 IN(SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL<E2.SAL);

 USE SCOTT;
 -- waqtd 5th minimum salry
	SELECT E1.SAL
    FROM EMP E1
    WHERE 5-1 IN(SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL > E2.SAL);

-- waqtd details of employee who is earning 7th maximum salary
SELECT *
FROM EMP E1
WHERE 7-1 IN(SELECT COUNT(DISTINCT E2.SAL)
FROM EMP E2
WHERE E1.SAL<E2.SAL);


-- QUERY TO DISPLAY 4 AND 5TH MAXIMUM SALARY

SELECT E1.SAL
FROM EMP E1
WHERE 4-1 IN(SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL < E2.SAL)
 OR  5-1 IN(SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL < E2.SAL);

SELECT E1.SAL
FROM EMP E1
WHERE (SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL < E2.SAL) IN (3,4);

-- waqtd first 5 maximum salaries
SELECT DISTINCT E1.SAL
FROM EMP E1
WHERE (SELECT COUNT(DISTINCT E2.SAL)
FROM EMP E2
WHERE E1.SAL<E2.SAL)<5;

-- WAQTD 3RD MAXIMUM AND 4TH MINIMUM SALARY
SELECT DISTINCT E1.SAL
FROM EMP E1
WHERE 3-1 IN(SELECT COUNT(DISTINCT E2.SAL)
FROM EMP E2
WHERE E1.SAL<E2.SAL) OR 4-1 IN(SELECT COUNT(DISTINCT E2.SAL)
FROM EMP E2
WHERE E1.SAL>E2.SAL);

-- WAQTD maxmium salary from each dept
SELECT DEPTNO, MAX(SAL) AS MAXSAL
FROM EMP
GROUP BY DEPTNO;

-- WAQTD 2ND MAXIUM SALARY OF EACH DEPT
SELECT DEPTNO, MAX(SAL) AS SECONDMAXSAL
FROM EMP E1
WHERE SAL < (
    SELECT MAX(SAL)
    FROM EMP E2
    WHERE E1.DEPTNO= E2.DEPTNO
)
GROUP BY DEPTNO;

--  WAQTD DETIALS OF EMPLOYEE WHOSE SALARY IS GREATER THAN THE AVG SAL OF THE TABLE.

SELECT E1.*
FROM EMP E1
WHERE SAL >(SELECT AVG(SAL) FROM EMP );

-- WAQTD DETAILS OF EMPLOYEE WHOSE SLARY IS GREATER THAN THE AVG SALAY ON THEIR DEPTNO


SELECT *
FROM EMP E1
WHERE SAL > (
    SELECT AVG(SAL) 
    FROM EMP E2 
    WHERE E2.DEPTNO = E1.DEPTNO
);

-- FUNCTION
-- WAQ FOR SUBSTRING
SELECT SUBSTRING(ENAME, 1,2) AS SUB_STRING
FROM EMP;

-- WAQTD FIRST 3 CHARCTER FROM THE EMPLOYEE JOBS
-- QUERY TO DISLAY LAST THREE CHARCTER FROM EMPLOYEE NAMES
SELECT SUBSTRING(ENAME,-3) AS LastThreeChars -- OR WE CAN USE SUBSTRING(ENAME, LENGTH(ENAME)-2,3)
FROM EMP;
-- OR

SELECT RIGHT(ENAME,3)
FROM EMP;

-- WAQTD LOC WHERE FIRST AND LAST CHARACTER IS VOWEL
SELECT LOC
FROM DEPT
WHERE SUBSTRING(LOC, 1, 1) IN ('A','E','I','O','U')
  AND SUBSTRING(LOC, -1) IN ('A','E','I','O','U');  -- OR SUBSTRING(LOC,LENGTH(LOC),1);

SELECT INSTR(ENAME, 'AR')
FROM EMP;

-- WAQTD NUMBER OF TIME CHARCTER 'A' IS PRESENT IN YASHRAJ STRING;
SELECT LENGTH('YASHRAJ') - LENGTH(REPLACE('YASHRAJ', 'A', '')) AS count_of_A
FROM DUAL;
 
 -- WAQTD DETAILS OF EMPLOYEE IF THEY HAVE CAHARCTER 'L' IN THEIR NAME;
 
 SELECT * 
 FROM EMP
 WHERE LENGTH(ENAME) - LENGTH(REPLACE(ENAME,'L','')) = 2;
 
 -- WAQTD TOTAL SALRY OF EACH EMPLYEE
 
SELECT ENAME,
       SAL + COALESCE(COMM, 0) AS TOTAL
FROM EMP;

-- CREATE TWO TABLE NAME THEM PRODUCT AND ANOTHER ONE IS CUSTOMER
-- PRODUCT: PID, PNAME, PRICE
-- CUSTOMER CID, CNAME, PH NO;



 
 